[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  data-integrator/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:39:26Z

App              Version  Status  Scale  Charm            Channel        Rev  Address         Exposed  Message
application               active      1  application                       0                  no       
config-server             active      1  mongodb-k8s      6/edge          58  10.152.183.129  no       
data-integrator           active      1  data-integrator  latest/stable   41  10.152.183.92   no       
mongos-k8s                active      1  mongos-k8s                        0  10.152.183.91   no       
shard0                    active      1  mongodb-k8s      6/edge          58  10.152.183.232  no       Primary

Unit                Workload  Agent  Address       Ports  Message
application/0*      active    idle                        
config-server/0*    active    idle   10.1.134.141         
data-integrator/0*  active    idle   10.1.134.145         
mongos-k8s/0*       active    idle   10.1.134.136         
shard0/0*           active    idle   10.1.134.142         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:31:24 ERROR unit.config-server/0.juju-log config-server:4: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729042283, 2), 'signature': {'hash': b'\\xa8\\xc1r\\xc0\\xff\\xa0\\xec\\xdbh\\xc5 \\xf8*\\xf5\\x10k\\xc5K\\xa6\\xc1', 'keyId': 7426179839842844697}}, 'operationTime': Timestamp(1729042283, 2)}")
unit-config-server-0: 01:31:24 ERROR unit.config-server/0.juju-log config-server:4: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:38:10 ERROR unit.mongos-k8s/0.juju-log External configuration: nonsensical-setting for expose-external is not valid, should be one of: ['none', 'nodeport']

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...