[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  mongos-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  mongos-k8s/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:38:28Z

App            Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
config-server           active      1  mongodb-k8s  6/edge    60  10.152.183.161  no       
mongos-k8s              active      2  mongos-k8s              0  10.152.183.251  no       
shard0                  active      1  mongodb-k8s  6/edge    60  10.152.183.122  no       

Unit              Workload  Agent  Address       Ports  Message
config-server/0*  active    idle   10.1.245.141         
mongos-k8s/0*     active    idle   10.1.245.136         
mongos-k8s/1      active    idle   10.1.245.143         
shard0/0*         active    idle   10.1.245.142         

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:33:43 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729647222, 1), 'signature': {'hash': b'\\xd5\\x8aY\\x88\\x17$a\\x98.*8\\xcc\\x9f\\xadN\\\\Y\\xc3\\x0b\\xba', 'keyId': 7428778020179017753}}, 'operationTime': Timestamp(1729647222, 1)}")
unit-config-server-0: 01:33:43 ERROR unit.config-server/0.juju-log config-server:6: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:35:24 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:36:26 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...