[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  mongos-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  mongos-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  self-signed-certificates-separate/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] blocked: mongos requires TLS to be enabled.
  mongos-k8s/1 [idle] blocked: mongos requires TLS to be enabled.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [executing] maintenance: enabling TLS
  mongos-k8s/1 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] waiting: Waiting for MongoDB to start
  mongos-k8s/1 [idle] blocked: mongos CA and Config-Server CA don't match.
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:06:31Z

App                                Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
config-server                               active       1  mongodb-k8s               6/edge          60  10.152.183.91   no       
mongos-k8s                                  waiting      2  mongos-k8s                                 0  10.152.183.61   no       installing agent
self-signed-certificates                    active       1  self-signed-certificates  latest/edge    202  10.152.183.105  no       
self-signed-certificates-separate           active       1  self-signed-certificates  latest/stable  155  10.152.183.88   no       
shard0                                      active       1  mongodb-k8s               6/edge          60  10.152.183.235  no       

Unit                                  Workload  Agent  Address       Ports  Message
config-server/0*                      active    idle   10.1.182.205         Primary
mongos-k8s/0*                         blocked   idle   10.1.182.200         mongos CA and Config-Server CA don't match.
mongos-k8s/1                          blocked   idle   10.1.182.207         mongos CA and Config-Server CA don't match.
self-signed-certificates-separate/0*  active    idle   10.1.182.209         
self-signed-certificates/0*           active    idle   10.1.182.208         
shard0/0*                             active    idle   10.1.182.206         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:32:23 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729560741, 2), 'signature': {'hash': b'\\x8e\\xcf\\xc4\\xf4\\xc1\\xa0#\\x04v}pH\\x00\\xe7\\xf7\\xe1\\xe9\\x9e\\xfcJ', 'keyId': 7428406595702226969}}, 'operationTime': Timestamp(1729560741, 2)}")
unit-config-server-0: 01:32:23 ERROR unit.config-server/0.juju-log config-server:6: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-1: 01:34:05 ERROR unit.mongos-k8s/1.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:34:06 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-1: 01:35:08 ERROR unit.mongos-k8s/1.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:35:08 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-1: 01:35:14 ERROR unit.mongos-k8s/1.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/./src/charm.py", line 977, in <module>
    main(MongosCharm)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/lib/charms/mongodb/v0/config_server_interface.py", line 346, in _on_relation_changed
    self._update_k8s_users(event)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/lib/charms/mongodb/v0/config_server_interface.py", line 354, in _update_k8s_users
    self.charm.client_relations.oversee_users(None, None)
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/lib/charms/mongodb/v1/mongodb_provider.py", line 197, in oversee_users
    with MongoConnection(self.charm.mongo_config) as mongo:
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/lib/charms/mongodb/v0/mongo.py", line 174, in __init__
    uri = config.uri
  File "/var/lib/juju/agents/unit-mongos-k8s-1/charm/lib/charms/mongodb/v0/mongo.py", line 121, in uri
    f"mongodb://{quote_plus(self.username)}:"
  File "/usr/lib/python3.10/urllib/parse.py", line 897, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/lib/python3.10/urllib/parse.py", line 881, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.10/urllib/parse.py", line 906, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
unit-mongos-k8s-1: 01:35:15 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongos-k8s-0: 01:37:02 ERROR unit.mongos-k8s/0.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:37:03 ERROR unit.mongos-k8s/0.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 01:37:03 ERROR unit.mongos-k8s/1.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 01:37:03 ERROR unit.mongos-k8s/1.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:42:01 ERROR unit.config-server/0.juju-log certificates:9: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:42:02 ERROR unit.config-server/0.juju-log certificates:9: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard0-0: 01:42:04 ERROR unit.shard0/0.juju-log certificates:10: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard0-0: 01:42:05 ERROR unit.shard0/0.juju-log certificates:10: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:53:06 ERROR unit.mongos-k8s/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-0: 01:53:06 ERROR unit.mongos-k8s/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-1: 01:53:08 ERROR unit.mongos-k8s/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-1: 01:53:08 ERROR unit.mongos-k8s/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-1: 01:53:10 ERROR unit.mongos-k8s/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-1: 01:53:10 ERROR unit.mongos-k8s/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-0: 01:53:28 ERROR unit.mongos-k8s/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-mongos-k8s-0: 01:53:28 ERROR unit.mongos-k8s/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-self-signed-certificates-0: 01:55:02 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "f0723dd3-792a-44e3-816b-b7720671243f:r#8#mongos-k8s": settings f0723dd3-792a-44e3-816b-b7720671243f:r#8#mongos-k8s not found (not found)
unit-mongos-k8s-0: 01:56:46 ERROR unit.mongos-k8s/0.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:56:46 ERROR unit.mongos-k8s/0.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 01:56:47 ERROR unit.mongos-k8s/1.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 01:56:47 ERROR unit.mongos-k8s/1.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 02:00:12 ERROR unit.mongos-k8s/1.juju-log certificates:12: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 02:00:13 ERROR unit.mongos-k8s/0.juju-log certificates:12: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 02:00:13 ERROR unit.mongos-k8s/0.juju-log certificates:12: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 02:00:13 ERROR unit.mongos-k8s/1.juju-log certificates:12: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-1: 02:04:58 ERROR unit.mongos-k8s/1.juju-log mongos is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-mongos-k8s-0: 02:06:29 ERROR unit.mongos-k8s/0.juju-log mongos is integrated to a different CA than the config server. Please use the same CA for all cluster components.

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...