[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  self-signed-certificates-separate/0 [allocating] waiting: installing agent
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:56:18Z

App                                Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
config-server                               active       1  mongodb-k8s               6/edge          54  10.152.183.27   no       Primary
mongos-k8s                                  waiting      1  mongos-k8s                                 0  10.152.183.134  no       installing agent
self-signed-certificates                    active       1  self-signed-certificates  latest/edge    192  10.152.183.238  no       
self-signed-certificates-separate           active       1  self-signed-certificates  latest/stable  155  10.152.183.45   no       
shard0                                      active       1  mongodb-k8s               6/edge          54  10.152.183.52   no       Primary

Unit                                  Workload  Agent  Address       Ports  Message
config-server/0*                      active    idle   10.1.158.140         Primary
mongos-k8s/0*                         waiting   idle   10.1.158.136         Waiting for MongoDB to start
self-signed-certificates-separate/0*  active    idle   10.1.158.144         
self-signed-certificates/0*           active    idle   10.1.158.143         
shard0/0*                             active    idle   10.1.158.142         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:30:44 ERROR unit.config-server/0.juju-log config-server:4: Failed to add shard shard0 to the config server, error=OperationFailure('Authentication failed., full error: {\'ok\': 0.0, \'errmsg\': \'Authentication failed.\', \'code\': 18, \'codeName\': \'AuthenticationFailed\', \'$clusterTime\': {\'clusterTime\': Timestamp(1727141444, 2), \'signature\': {\'hash\': b\'\\xb0\\xe4\\xc3\\xd4\\xe0\\xc6-\\xbd!\\x86\\xb2\\x1c\\xc4\\\'\\xf7a\\xa9\\x1d\\xff"\', \'keyId\': 7418015862927392793}}, \'operationTime\': Timestamp(1727141444, 2)}')
unit-config-server-0: 01:30:44 ERROR unit.config-server/0.juju-log config-server:4: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:35:38 ERROR unit.mongos-k8s/0.juju-log certificates:6: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:35:38 ERROR unit.mongos-k8s/0.juju-log certificates:6: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:38:35 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard0-0: 01:38:36 ERROR unit.shard0/0.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:38:36 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard0-0: 01:38:36 ERROR unit.shard0/0.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:42:01 ERROR unit.mongos-k8s/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-mongos-k8s-0: 01:42:01 ERROR unit.mongos-k8s/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-mongos-k8s-0: 01:48:20 ERROR unit.mongos-k8s/0.juju-log certificates:9: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:48:20 ERROR unit.mongos-k8s/0.juju-log certificates:9: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-self-signed-certificates-0: 01:51:01 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "e38962a1-858b-4a4e-8445-e4ceb60a3e32:r#9#mongos-k8s": settings e38962a1-858b-4a4e-8445-e4ceb60a3e32:r#9#mongos-k8s not found (not found)
unit-mongos-k8s-0: 01:51:19 ERROR unit.mongos-k8s/0.juju-log certificates:10: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-mongos-k8s-0: 01:51:19 ERROR unit.mongos-k8s/0.juju-log certificates:10: Non-existing secret unit:ext-cert-secret was attempted to be removed.

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...